### ISSUE TITLE
Error - Formatter (Ok:0|fail:1)

### ISSUE THREAD

**Issue by NatashaSteele** [bitst0rm-pub/Formatter#1]
How to know what error I made?
I installed the required plugins in the default locale for each of them according to the default configuration.

Something I did not find was where to set the path of node.js, the rest I did as the default.

thanks.

Below is a debug:

▋[Formatter](Thread-16:formatter.py#L83): [DEBUG] Target: D:\www\admindeck\public_html\default\dashboard-crm.html
▋[Formatter](Thread-16:formatter.py#L84): [DEBUG] Scope: text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
▋[Formatter](Thread-16:formatter.py#L85): [DEBUG] Syntax: html
▋[Formatter](Thread-16:formatter.py#L86): [DEBUG] Formatter ID: jsbeautifier
▋[Formatter](Thread-16:common.py#L248): [DEBUG] Config [default]: C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\jsbeautifyrc.json
▋[Formatter](Thread-16:formatter_jsbeautifier.py#L69): [ERROR] File not formatted due to an error (errno=1): "C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\javascript\node_modules\.bin\js-beautify:2

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
"
▋[Formatter](Thread-16:main.py#L118): [DEBUG] Formatting failed. 💣💥😢

**Comment by bitst0rm** [comment]
Hi,
You do not need to set the path to interpreter like node.exe, php.exe... By default installation, Formatter will see them. If not, i will see it in the bug report. By custom installation, you can use the `PATH` option:
```
    "environ": {
        "PATH": ["C:\Users\steel\path\to\__folder__\where\the\interpreter\is\"],
    },
```
In your case `node.js` has been recognized by Formatter. The communication between them has been made. Node want to talk with js-beautifier, but falls on this line:

`"C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\javascript\node_modules.bin\js-beautify:2`

Please check your `"executable_path":` in Formatter settings, it should be (missing `\`):
`C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\javascript\node_modules\.bin\js-beautify`

**Comment by NatashaSteele** [comment]
> Hi,
> You do not need to set the path to interpreter like node.exe, php.exe... By default installation, Formatter will see them. If not, i will see it in the bug report. By custom installation, you can use the `PATH` option:
> 
> ```
>     "environ": {
>         "PATH": ["C:\Users\steel\path\to\__folder__\where\the\interpreter\is\"],
>     },
> ```
> In your case `node.js` has been recognized by Formatter. The communication between them has been made. Node want to talk with js-beautifier, but falls on this line:
> 
> `"C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\javascript\node_modules.bin\js-beautify:2`
> 
> Please check your `"executable_path":` in Formatter settings, it should be (missing `\`):
> `C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\javascript\node_modules\.bin\js-beautify`

**Comment by NatashaSteele** [comment]
Please, I have no idea what to do.
I have already installed all the formatters by npm in Node.js but nothing.

▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_beautysh
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_black
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_clangformat
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_cleancss
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_csscomb
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_eslint
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_htmlminifier
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_htmltidy
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_jsbeautifier
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_jsonmax
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_jsonmin
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_perltidy
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_phpcsfixer
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_prettier
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_rubocop
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_stylelint
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_terser
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_uncrustify
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter_yapf
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.formatter
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.src.common
▋[Formatter](Dummy-5:common.py#L63): [DEBUG] Reloading: Formatter.main
reloading settings Packages/User/Formatter.sublime-settings
no such prop row_padding for icon_file_type
no such prop row_padding for icon_file_type
▋[Formatter](MainThread:main.py#L53): [DEBUG] Starting a new thread ...
▋[Formatter](Thread-148:main.py#L110): [DEBUG] Environment: {'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\steel\\AppData\\Roaming',
 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey',
 'CHOCOLATEYLASTPATHUPDATE': 'qua out  3 12:41:25 2018',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'NATASHA',
 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'GEM_PATH': 'C:\\Users\\steel\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\formatter.assets\\ruby',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\steel',
 'LOCALAPPDATA': 'C:\\Users\\steel\\AppData\\Local',
 'LOGONSERVER': '\\\\NATASHA',
 'NUMBER_OF_PROCESSORS': '8',
 'ONEDRIVE': 'C:\\Users\\steel\\OneDrive',
 'OS': 'Windows_NT',
 'PATH': 'D:\\Nodejs\\;D:\\Php;D:\\Tidy\\bin;D:\\PuTTY;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\ManagementStudio\\;C:\\ProgramData\\chocolatey\\bin;D:\\nodejs;D:\\Git;C:\\Users\\steel\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\steel\\AppData\\Roaming\\npm;C:\\Users\\steel\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Users\\steel\\AppData\\Roaming\\Composer\\vendor\\bin',
 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
 'PROCESSOR_ARCHITECTURE': 'AMD64',
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 9, GenuineIntel',
 'PROCESSOR_LEVEL': '6',
 'PROCESSOR_REVISION': '9e09',
 'PROGRAMDATA': 'C:\\ProgramData',
 'PROGRAMFILES': 'C:\\Program Files',
 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
 'PROGRAMW6432': 'C:\\Program Files',
 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\PowerShell\\Modules\\',
 'PUBLIC': 'C:\\Users\\Public',
 'PYTHONPATH': 'C:\\Users\\steel\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\formatter.assets\\python\\lib\\python3.7\\site-packages',
 'SYSTEMDRIVE': 'C:',
 'SYSTEMROOT': 'C:\\Windows',
 'TEMP': 'C:\\Temp',
 'TMP': 'C:\\Temp',
 'USERDOMAIN': 'NATASHA',
 'USERDOMAIN_ROAMINGPROFILE': 'NATASHA',
 'USERNAME': 'steel',
 'USERPROFILE': 'C:\\Users\\steel',
 'WINDIR': 'C:\\Windows',
 '__COMPAT_LAYER': 'RunAsAdmin'}
▋[Formatter](Thread-148:formatter.py#L83): [DEBUG] Target: D:\www\admindeck\public_html\default\chart-nvd3.html
▋[Formatter](Thread-148:formatter.py#L84): [DEBUG] Scope: text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
▋[Formatter](Thread-148:formatter.py#L85): [DEBUG] Syntax: html
▋[Formatter](Thread-148:formatter.py#L86): [DEBUG] Formatter ID: htmltidy
▋[Formatter](Thread-148:common.py#L242): [DEBUG] Config [html]: C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\htmltidyrc_html.cfg
▋[Formatter](Thread-148:formatter_htmltidy.py#L62): [ERROR] File not formatted due to an error (errno=1): "Warning: replacing invalid character code 128


Warning: replacing invalid character code 128
Warning: replacing invalid character code 128
Warning: replacing invalid character code 128
Warning: replacing invalid character code 134
Warning: replacing invalid character code 134
Warning: replacing invalid character code 134
Warning: replacing invalid character code 134
Warning: replacing invalid character code 134
Warning: replacing invalid character code 134
Warning: replacing invalid character code 128
Config: unknown option: <a role="menuitem" class="dropdown-item" href="https
Warning: replacing invalid character code 159
Warning: replacing invalid character code 140
Warning: replacing invalid character code 159
Warning: replacing invalid character code 146
Warning: replacing invalid character code 159
Warning: discarding invalid character code 143
Warning: replacing invalid character code 159
Warning: replacing invalid character code 142
Warning: replacing invalid character code 128
Warning: replacing invalid character code 153

line 6 column 1 - Warning: discarding unexpected <head>
line 61 column 1 - Warning: trimming empty <i>
line 64 column 1 - Warning: trimming empty <i>
line 73 column 2 - Warning: trimming empty <i>
line 72 column 1 - Warning: trimming empty <span>
line 77 column 1 - Warning: trimming empty <i>
line 76 column 1 - Warning: trimming empty <span>
line 84 column 1 - Warning: trimming empty <i>
line 92 column 1 - Warning: trimming empty <i>
line 136 column 1 - Warning: trimming empty <i>
line 146 column 1 - Warning: trimming empty <i>
line 151 column 1 - Warning: trimming empty <i>
line 156 column 1 - Warning: trimming empty <i>
line 161 column 1 - Warning: trimming empty <i>
line 166 column 1 - Warning: trimming empty <i>
line 171 column 1 - Warning: trimming empty <i>
line 188 column 1 - Warning: trimming empty <i>
line 194 column 72 - Warning: trimming empty <i>
line 194 column 1 - Warning: trimming empty <button>
line 255 column 1 - Warning: trimming empty <i>
line 295 column 72 - Warning: trimming empty <i>
line 295 column 1 - Warning: trimming empty <button>
line 312 column 28 - Warning: trimming empty <i>
line 312 column 1 - Warning: trimming empty <span>
line 336 column 28 - Warning: trimming empty <i>
line 336 column 1 - Warning: trimming empty <span>
line 405 column 1 - Warning: trimming empty <i>
line 404 column 1 - Warning: trimming empty <span>
line 413 column 1 - Warning: trimming empty <i>
line 412 column 1 - Warning: trimming empty <span>
line 442 column 1 - Warning: trimming empty <i>
line 441 column 1 - Warning: trimming empty <span>
line 522 column 1 - Warning: trimming empty <i>
line 521 column 1 - Warning: trimming empty <span>
line 587 column 1 - Warning: trimming empty <i>
line 586 column 1 - Warning: trimming empty <span>
line 612 column 1 - Warning: trimming empty <i>
line 611 column 1 - Warning: trimming empty <span>
line 620 column 1 - Warning: trimming empty <i>
line 619 column 1 - Warning: trimming empty <span>
line 648 column 1 - Warning: trimming empty <i>
line 647 column 1 - Warning: trimming empty <span>
line 678 column 1 - Warning: trimming empty <i>
line 677 column 1 - Warning: trimming empty <span>
line 687 column 1 - Warning: trimming empty <i>
line 686 column 1 - Warning: trimming empty <span>
line 695 column 1 - Warning: trimming empty <i>
line 694 column 1 - Warning: trimming empty <span>
line 703 column 2 - Warning: trimming empty <i>
line 702 column 1 - Warning: trimming empty <span>
line 714 column 1 - Warning: trimming empty <i>
line 713 column 1 - Warning: trimming empty <span>
line 744 column 1 - Warning: trimming empty <i>
line 743 column 1 - Warning: trimming empty <span>
line 794 column 1 - Warning: trimming empty <i>
line 793 column 1 - Warning: trimming empty <span>
line 866 column 1 - Warning: trimming empty <i>
line 865 column 1 - Warning: trimming empty <span>
line 874 column 1 - Warning: trimming empty <i>
line 873 column 1 - Warning: trimming empty <span>
line 929 column 1 - Warning: trimming empty <i>
line 928 column 1 - Warning: trimming empty <span>
line 940 column 1 - Warning: trimming empty <i>
line 939 column 1 - Warning: trimming empty <span>
line 1010 column 1 - Warning: trimming empty <i>
line 1009 column 1 - Warning: trimming empty <span>
line 1043 column 1 - Warning: trimming empty <i>
line 1042 column 1 - Warning: trimming empty <span>
line 1073 column 1 - Warning: trimming empty <i>
line 1072 column 1 - Warning: trimming empty <span>
line 1098 column 1 - Warning: trimming empty <i>
line 1097 column 1 - Warning: trimming empty <span>
line 1126 column 1 - Warning: trimming empty <i>
line 1125 column 1 - Warning: trimming empty <span>
line 1137 column 1 - Warning: trimming empty <i>
line 1136 column 1 - Warning: trimming empty <span>
line 1157 column 1 - Warning: trimming empty <i>
line 1156 column 1 - Warning: trimming empty <span>
line 1178 column 1 - Warning: trimming empty <i>
line 1187 column 1 - Warning: trimming empty <i>
line 1186 column 1 - Warning: trimming empty <span>
line 1195 column 1 - Warning: trimming empty <i>
line 1194 column 1 - Warning: trimming empty <span>
line 1207 column 1 - Warning: trimming empty <i>
line 1206 column 1 - Warning: trimming empty <span>
line 1239 column 1 - Warning: trimming empty <i>
line 1248 column 1 - Warning: trimming empty <i>
line 1247 column 1 - Warning: trimming empty <span>


line 1264 column 1 - Warning: trimming empty <i>


line 1275 column 22 - Warning: trimming empty <i>
line 15 column 1 - Warning: discarding unexpected <meta>
Info: Document content looks like HTML5

Tidy found 91 warnings and 0 errors!

Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the 
specified encoding and replaced that reference with the Unicode 
equivalent.


One or more empty elements were present in the source document but
dropped on output. If these elements are necessary or you don't want
this behavior, then consider setting the option "drop-empty-elements"
to no.


About HTML Tidy: https://github.com/htacg/tidy-html5

Bug reports and comments: https://github.com/htacg/tidy-html5/issues
Official mailing list: https://lists.w3.org/Archives/Public/public-htacg/
Latest HTML specification: http://dev.w3.org/html5/spec-author-view/
Validate your HTML documents: http://validator.w3.org/nu/
Lobby your company to join the W3C: http://www.w3.org/Consortium


Do you speak a language other than English, or a different variant of 
English? Consider helping us to localize HTML Tidy. For details please see 


https://github.com/htacg/tidy-html5/blob/master/README/LOCALIZE.md
"
▋[Formatter](Thread-148:main.py#L118): [DEBUG] Formatting failed. 💣💥😢
no such prop row_padding for icon_file_type


Config file:

/ Do NOT edit anything in the left-hand pane.
// Copy the whole tree from there to here.
{
    "debug": true,
    "show_statusbar": true,
    "environ": {
        "PATH": [],
        "GEM_PATH": ["${packages}/User/formatter.assets/ruby"],
        "PYTHONPATH": ["${packages}/User/formatter.assets/python/lib/python3.7/site-packages"]
    },

    // Formatter specific settings
    "formatters": {

        "htmltidy": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["html", "xml"],
            "executable_path": "D:/Tidy/bin/tidy.exe",
            "config_path": {
                "html": "${packages}/User/formatter.assets/config/htmltidyrc_html.cfg",
                "xml": "${packages}/User/formatter.assets/config/htmltidyrc_xml.cfg"
            }
        },
        "jsbeautifier": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["js", "css", "html", "json"],
            "executable_path": "C:/Users/steel/AppData/Roaming/npm/js-beautify",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/jsbeautifyrc.json"
            }
        },
        "phpcsfixer": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["php"],
            "executable_path": "D:/Php/php-cs-fixer-v2.phar",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/phpcsfixerrc.php"
            }
        },
        "prettier": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["css", "scss", "less", "js", "jsx", "json", "html", "graphql", "markdown", "tsx", "vue", "yaml"],
            "executable_path": "C:/Users/steel/AppData/Roaming/npm/prettier",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/prettierrc.json"
            }
        },
        "stylelint": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["css", "scss", "sass", "less", "sss", "sugarss"],
            "executable_path": "C:/Users/steel/AppData/Roaming/npm/stylelint",
            "args": ["--config-basedir", "C:/Users/steel/AppData/Roaming/npm/node_modules"],
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/stylelintrc.json"
            }
        },
        "cleancss": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["css", "scss", "sass", "less"],
            "executable_path": "C:/Users/steel/AppData/Roaming/npm/cleancss",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/cleancssrc.json"
            }
        },
        "htmlminifier": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["html", "xml"],
            "executable_path": "C:/Users/steel/AppData/Roaming/npm/html-minifier",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/htmlminifierrc.json"
            }
        }
    }
}

**Comment by bitst0rm** [comment]
Thanks for the bug report. I fixed the issue to htmltidy and released a new build (v.0.1.5). You will get the new version via Packages Control soon.

If you just need to indent html code, then you can adjust the `htmltidyrc_html.cfg` like so:
```
indent: auto
indent-spaces: 4
quiet: yes
tidy-mark: no
force-output: yes
show-errors: 0
show-warnings: 0
```
https://stackoverflow.com/questions/7151180/use-html-tidy-to-just-indent-html-code

**Comment by NatashaSteele** [comment]
> btw, you do not need to set `"GEM_PATH"` and `"PYTHONPATH"` for the current plugins you are using - all node related. Omit/Set them empty like so could not be wrong:
> 
> ```
> "environ": {
> "PATH": []
> },
> ```

But these values are by default, I did not.

**Comment by NatashaSteele** [comment]
▋[Formatter](Thread-23:formatter.py#L83): [DEBUG] Target: D:\www\admindeck\public_html\default\dashboard-crm.html
▋[Formatter](Thread-23:formatter.py#L84): [DEBUG] Scope: text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
▋[Formatter](Thread-23:formatter.py#L85): [DEBUG] Syntax: html
▋[Formatter](Thread-23:formatter.py#L86): [DEBUG] Formatter ID: htmltidy
▋[Formatter](Thread-23:common.py#L242): [DEBUG] Config [html]: C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\htmltidyrc_html.cfg
▋[Formatter](MainThread:main.py#L126): [DEBUG] Replacing text ...
▋[Formatter](Thread-23:main.py#L115): [DEBUG] Formatting successful. 🎉😃🍰

**Comment by bitst0rm** [comment]
```
▋Formatter: [ERROR] File not formatted due to an error (errno=1): "D:\nodejs.npm\prettier:2

basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")

      ^^^^^^^
SyntaxError: missing ) after argument list
```
I could reproduce the issue above on windows. A quick search via google gave me at least a handfull of people who got the same error. Using the pure Command Prompt (cmd.exe) i got the same error, also Formatter has nothing to do with this issue. This error comes from 3rd party plugins using node, or node itself.
Here is the solution:

- **jsbeautifier:**

    from:

    - `"executable_path": "C:/Users/steel/AppData/Roaming/npm/js-beautify",`

    change to:

    - `"executable_path": "%AppData%/npm/js-beautify/js/lib/cli.js",`

    (A shortcut for `C:/Users/steel/AppData/Roaming/` = `%AppData%`)

    or from:

    - "executable_path": "D:/nodejs/.npm/js-beautify",

    change to:

    - "executable_path": "D:/nodejs/.npm/node_modules/js-beautify/js/lib/**cli.js**",


- **prettier:**

    from:

    - "executable_path": "C:/Users/steel/AppData/Roaming/npm/prettier",

    change to:

    - "executable_path": "%AppData%/npm/node_modules/prettier/**bin-prettier.js**",

On windows neither **prettier** (without extension) nor prettier.**cmd** seems to work when installed globally. The same for js-beautify, and maybe for all javascript modules using node.

**Comment by NatashaSteele** [comment]
Hi
With the configuration you passed worked correctly, thank you.
But the prettier of this error in the same file.

Thank you for your help.

```
 "jsbeautifier": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["js", "css", "html", "json"],
            "executable_path": "D:/nodejs/.npm/node_modules/js-beautify/js/lib/cli.js",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/jsbeautifyrc.json"
            }
        },
```

▋[Formatter](MainThread:main.py#L53): [DEBUG] Starting a new thread ...
▋[Formatter](Thread-239:main.py#L110): [DEBUG] Environment: {'ALLUSERSPROFILE': 'C:\\ProgramData',
 
▋[Formatter](Thread-239:formatter.py#L83): [DEBUG] Target: D:\www\admindeck\public_html\default\dashboard-analytics.html
▋[Formatter](Thread-239:formatter.py#L84): [DEBUG] Scope: text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
▋[Formatter](Thread-239:formatter.py#L85): [DEBUG] Syntax: html
▋[Formatter](Thread-239:formatter.py#L86): [DEBUG] Formatter ID: jsbeautifier
▋[Formatter](Thread-239:common.py#L215): [DEBUG] Interpreter: D:\nodejs\node.exe
▋[Formatter](Thread-239:common.py#L226): [DEBUG] Executable: D:\nodejs\.npm\node_modules\js-beautify\js\lib\cli.js
▋[Formatter](Thread-239:common.py#L249): [DEBUG] Config [default]: C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\jsbeautifyrc.json
▋[Formatter](MainThread:main.py#L126): [DEBUG] Replacing text ...
▋[Formatter](Thread-239:main.py#L115): [DEBUG] Formatting successful. 🎉😃🍰

```

"prettier": {
            "disable": false,
            "format_on_save": false,
            "syntaxes": ["css", "scss", "less", "js", "jsx", "json", "html", "graphql", "markdown", "tsx", "vue", "yaml"],
            "executable_path": "D:/nodejs/.npm/node_modules/prettier/bin-prettier.js",
            "config_path": {
                "default": "${packages}/User/formatter.assets/config/prettierrc.json"
            }
        },
```

▋[Formatter](Thread-328:formatter.py#L83): [DEBUG] Target: D:\www\admindeck\public_html\default\dashboard-analytics.html
▋[Formatter](Thread-328:formatter.py#L84): [DEBUG] Scope: text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
▋[Formatter](Thread-328:formatter.py#L85): [DEBUG] Syntax: html
▋[Formatter](Thread-328:formatter.py#L86): [DEBUG] Formatter ID: prettier
▋[Formatter](Thread-328:common.py#L215): [DEBUG] Interpreter: D:\nodejs\node.exe
▋[Formatter](Thread-328:common.py#L226): [DEBUG] Executable: D:\nodejs\.npm\node_modules\prettier\bin-prettier.js
▋[Formatter](Thread-328:common.py#L249): [DEBUG] Config [default]: C:\Users\steel\AppData\Roaming\Sublime Text 3\Packages\User\formatter.assets\config\prettierrc.json
▋[Formatter](Thread-328:formatter_prettier.py#L83): [ERROR] File not formatted due to an error (errno=2): "[error] tmpk0qaf5.html: SyntaxError: Unexpected closing tag "li". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (564:1)
[error]   562 | </a>
[error]   563 | </li>
[error] > 564 | </li>
[error]       | ^
[error]   565 | <li class=" ">
[error]   566 | <a href="modal.html" class="waves-effect waves-dark">
[error]   567 | <span class="pcoded-mtext">Modal</span>
"
▋[Formatter](Thread-328:main.py#L118): [DEBUG] Formatting failed. 💣💥😢

**Comment by bitst0rm** [comment]
Hi Natasha
The error occurred on line 564 because, Prettier detects that a `</li>`  tag too much.
You just delete this tag `</li>` on line 564, then all ok.

**Comment by NatashaSteele** [comment]
> The error occurred on line 564 because, Prettier detects that a `</li>` tag too much.
> You just delete this tag `</li>` on line 564, then all ok.

But why the js-beautifier and html tidy did not accuse the error?

**Comment by bitst0rm** [comment]
js-beautifier does not seem to check for correct syntax, it just parse the source code then format it. htmltidy does check for the correct syntax, but sometime it just interpret the error as warning.
This is a question of design and architecture, how the authors of such plugins write their code. At this point all errors and warnings, also the design how the formatted code looks, belong to 3rd party plugins and how you configure them. Formatter does not do this job. It does not format your source code. It just provides a interface to 3rd party plugins to do formatting code.

**Comment by NatashaSteele** [comment]
> js-beautifier does not seem to check for correct syntax, it just parse the source code then format it. htmltidy does check for the correct syntax, but sometime it just interpret the error as warning.
> This is a question of design and architecture, how the authors of such plugins write their code. At this point all errors and warnings, also the design how the formatted code looks, belong to 3rd party plugins and how you configure them. Formatter does not do this job. It does not format your source code. It just provides a interface to 3rd party plugins to do formatting code. This is how Formatter works:
> Natasha says: format me the code!!! >>> Formatter says: OK, madame, Htmltidy can do it. Here is your order, Htmltidy. Do it now for Natasha! I go to vacation yet >>> Htmltidy says: OK sir, good luck for your vacation, i format the code at my home now.

Okay, thanks for the explanation and I'm glad to have such an efficient tool.
Thank you.
