### ISSUE TITLE
latest sublimetext formatter-json bug

### ISSUE THREAD

**Issue by hatakes** [bitst0rm-pub/Formatter#18]
## Describe the bug:
![image](https://user-images.githubusercontent.com/26193001/120168498-81b15280-c231-11eb-9a50-4ffb49241bd7.png)

![image](https://user-images.githubusercontent.com/26193001/120168517-87a73380-c231-11eb-9b81-fe6b8fbe9823.png)
When I format with JSON, the Chinese characters will be transcoded
## Environment:

  - Sublime Text version:
  - Formatter version:
  - Plugins used (name, version):
  - Configuration (plugin, Formatter):
  
  - Operating System:

## Code sample:

```
?
```

## Log report:

```
?
```

**Comment by latewind** [comment]
modify the formatter_jsonmax.py file，add ensure_ascii=False  to the json.dumps method
