### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by Zontir** [bitst0rm-pub/Formatter#3]
I was trying to install this package for an hour on my Sublime Text 3 until I gave up. The truth is that you need to document better and give one or two examples of how to install this at least to the most popular languages that are php, js even html.
In this way we could guide ourselves much better.

Greetings!

**Comment by bitst0rm** [comment]
I can sum the installation process into 3 steps:
1. There are 3 ways to install Formatter, which is already described in the [Installation section](https://github.com/bitst0rm-pub/Formatter#installation) in the README.md.
2. After that, you need to install subplugins (e.g. PHP-CS-Fixer, JS-Beautifier etc...) to perform formatting. Formatter does not include any subplugins out-of-box as already said in the [Plugins section](https://github.com/bitst0rm-pub/Formatter#plugins).
It's **up to you** to install subplugins of your choice or not and where you want  install them in your machine. _How_ you install such subplugins is **not** under the responsibility and control of Formatter's author. Therefore it's not documented in the README.md. You might want to ask such subplugins's authors for more information how you can get **their** child into your machine. Issues and troubles to subplugins belong to subplugins's authors. Formatter has nothing to do with their problems. Links to them can be found in the [Plugins section](https://github.com/bitst0rm-pub/Formatter#plugins).
3. After that, you need to configure subplugins to talk with Formatter. In the [Configuration section](https://github.com/bitst0rm-pub/Formatter#configuration) you will see an example to Formatter setting. The most important key is `"executable_path":` here you set the path to your subplugin executable, so Formatter will see it in your machine.
From example:
`"executable_path": "${packages}/User/formatter.assets/bin/php-cs-fixer-v2.phar",`
applied to my current machine:
`"executable_path": "/Users/admin/Desktop/beauty/php/php-cs-fixer-v2.phar",`

that's all
best regards

**Comment by Zontir** [comment]
I have made the steps exactly the same as what you say above, that was the time I missed, the problem is that after configuring your plugin I can not make it work, even set the absolute path to executable. In my case I have it on the desktop as follows
`"executable_path": "C:/Users/admin/Desktop/php-cs-fixer-v2.phar",`

After that and execute Formatter in the command palette nothing happens.

**Comment by bitst0rm** [comment]
I need more info so please set Formatter setting to `"debug": true,`, restart Sublime, View > Show Console, hit the command that fails and post the log.

**Comment by bitst0rm** [comment]
In my case I have it on the desktop as follows
> `"executable_path": "C:/Users/admin/Desktop/php-cs-fixer-v2.phar",`

You seem to mix MacOSX with Windows.
