### ISSUE TITLE
[Plugin Request]Add Swift Format

### ISSUE THREAD

**Issue by RaffeYang** [bitst0rm-pub/Formatter#38]
Any plan to add [swiftformat](https://github.com/nicklockwood/SwiftFormat),There is already a separate plugin here[Sublime Swift Format](https://github.com/aerobounce/Sublime-Swift-Format)

**Comment by bitst0rm** [comment]
Hi @raffeyang 
It is now in the `master` branch and is ready for release.
Unfortunately, Sublime Text 4 still lacks support for Swift syntax highlighting.

**Comment by RaffeYang** [comment]
> Hi  你好@raffeyang It is now in the `master` branch and is ready for release.它现在在 `master` 分支中，可以发布。 Unfortunately, Sublime Text 4 still lacks support for Swift syntax highlighting.不幸的是，Sublime Text 4 仍然缺乏对 Swift 语法突出显示的支持。

Dear bitst0rm,

Thank you for your exceptional work and for being so responsive to the development requests of this community. I look forward to seeing how your work will continue to innovate in the future.

About the Swift syntax highlighting, the [Decent Swift Syntax](https://packagecontrol.io/packages/Decent%20Swift%20Syntax) works fine.

**Comment by bitst0rm** [comment]
Hi @raffeyang again,

Thank you, you are welcome.
I have added Swift REPL too. For this you will need to add:
```
    "interactive_repl": {
        "syntax": {
            "swift": "Packages/Decent Swift Syntax/Swift.sublime-syntax"
        },
```
in your User Settings.
- However, it appears that Swift doesn't support an interactive mode for running file.swift directly in the "Run current file".
- The reference config file `swiftformat_rc.cfg` is complete to use (References > Package settings > Formatter > Open Config Folders). This reference file could be overwritten by any updates, so you will need to copy it to use it as your final file.

I've just released version 1.0.15 so you can use it now.
For the time being, I'll consider this matter closed. Please don't hesitate to reopen it if you encounter any issues.

**Comment by raffeyang** [comment]
Thank you so much for your amazing work from which I have profoundly benefited. This is indeed an impressive project, and I sincerely appreciate your hard work and effort!

My question might seem a little off-topic, but I would like to ask about the process of deactivating or hiding unused REPLs, such as CoffeeScript, in my project? I would prefer to only display the REPLs that I am using. Could you please let me know if this is possible, and if so, how can this be done?

Once again, I am truly appreciative of your fantastic work and am looking forward to your response!

**Comment by RaffeYang** [comment]
@bitst0rm 
Thank you so much for your amazing work from which I have profoundly benefited. This is indeed an impressive project, and I sincerely appreciate your hard work and effort!

I found the "Run current file" works well with swift, but "Terminal" not work.
```bash

Welcome to Swift!

Subcommands:

  swift build      Build Swift packages
  swift package    Create and work on packages
  swift run        Run a program from a package
  swift test       Run package tests
  swift repl       Experiment with Swift code interactively

  Use `swift --help` for descriptions of available options and flags.

  Use `swift help <subcommand>` for more information about a subcommand.

>>> 
*** Non-interactive REPL closed ***
```
My another question might seem a little off-topic, but I would like to ask about the process of deactivating or hiding unused REPLs, such as CoffeeScript, in my project? I would prefer to only display the REPLs that I am using. Could you please let me know if this is possible, and if so, how can this be done?

Once again, I am truly appreciative of your fantastic work and am looking forward to your response!

**Comment by bitst0rm** [comment]
@raffeyang 
The Terminal issue has already been fixed some time ago and just waiting for the release.
Unfortunately, it is not possible to deactivate or hide unused menu items if those items have child elements ("Run current file" and "Terminal"). This limitation is the sad part of ST's architectural design. Many developers have requested this change for years, but there hasn't been a positive response from the creator of ST.
For now 1.0.16 is on the way to you.
