### ISSUE TITLE
Formatter interferes with ApplySyntax plugin

### ISSUE THREAD

**Issue by macfreek** [bitst0rm-pub/Formatter#39]
I have both this Formatter package installed in SublimeText (build 4152), as well as the [ApplySyntax package](https://facelessuser.github.io/ApplySyntax/). ApplySyntax applies a syntax based on other attributes than the extension. For example, I use to to apply a "Ansible" syntax to YAML files which contain an Ansible playbook.

However, Formatter interferes with this behaviour. When I load a file, this happens:

    ApplySyntax: Syntax set to Ansible using Packages/Ansible/Ansible.sublime-syntax
    Formatter: Restore syntax to Packages/YAML/YAML.sublime-syntax

The latter is caused by a call to `view.set_syntax_file()` in [`SessionManager.restore_syntax()`](https://github.com/bitst0rm-pub/Formatter/blob/26b91d30288f577ee7156b4cc4f203fecaadbabd/core/smanager.py#L111C13-L111C13).

Why is Formatter doing this, and how can I disable this unwanted behaviour?

**Comment by bitst0rm** [comment]
Hi @macfreek 

I was able to reproduce the issue using Ansible.sublime-syntax and the ApplySyntax package.
`set_syntax_file()` has been deprecated by Sublime Text.
I have released version 1.0.17 to address this issue.
It should be in the next hour on the packagecontrol.io

**Comment by macfreek** [comment]
Hi @bitst0rm, thanks for the lightning fast reply!

Unfortunately, 1.0.17 does not seem to fix the issue.
It seems that Formatter has a feature that retains state, even when closing and opening a file. I hadn't realised this before.

Here is a way to reproduce it:

1. At start, make sure ApplySyntax is **not** configured yet.
2. Open a file, let's say `my_playbook.yml`. Since ApplySyntax is not yet configured, SublimeText shows it with YAML syntax.
3. Close the file. At this moment, Formatter stores the session details (selection, bookmark, and syntax) in `Local/Session.formatter_session`.
4. Configure ApplySyntax to apply Ansible syntax to files called `*playbook*.yml`
5. Reopen the file
6. ApplySyntax applies the Ansible syntax to the file, as it should.
7. Formatter reads the stored session details, and re-applies the YAML syntax, as recorded in the session file.

So my issue is with the session-restore feature of Formatter. While I love the formatting capability of the Formatter, the session-restoration feature was a surprise to me (such a feature may warrants it's own package in my view).

I understand that this is a great feature for many people, but I personally like to turn it off. Is that possible?

Thanks!

**Comment by macfreek** [comment]
I found the way to turn off the session restore feature:

    "remember_session": false,

In the mean time, I'll think of a better way to deal with this situation, as it only occurs when ApplySyntax is newly installed or if the settings of ApplySyntax is changed while the syntax is stored in the Formatter session file.

I also found some off behaviour (where the session is not always restored).

**Comment by bitst0rm** [comment]
Hi @macfreek again,

Thank you for your detailed description. Formatter includes 3 bonus features that are not part of its main purpose but may be helpful for some people in tracking bugs while formatting and beyond:
- The word counter (can be disabled in settings)
- This session remember (can be disabled in settings)
- The interactive REPL (experimental)

As you may already be aware, the 3. step is the most important where the session manager saves the current final state. After that, in step 4., 5., 6. the session manager does not know and does not care about any syntax changes during this time. Extending the steps to:
8. Switch to Ansible syntax
9. Close the file. At this point, those changes will be taken into account and the Ansible syntax will be recorded in `Session.formatter_session`

The logic of this feature is to retain the state only at the moment of closing a file. So, I believe the only way to deal with this situation is to disable `"remember_session": false`, as you have already done.

**Comment by MatthiasPortzel** [comment]
This session-restore behavior was very surprising to me. The edge cases are not limited to ApplySyntax.

Other undesirable cases I've hit include:
* After uninstalling a syntax package. Formatter throws an error any time opening a file that used to be handled by that syntax package, as it tries to apply a syntax that doesn't exist any more.
* Installing a syntax package. If you open a file you don't have a syntax for, then install a syntax that supports that file, Formatter will keep the file highlighted as Plain Text.

I can imagine some cases where the session restore in general is useful, but this behavior of "restoring" a syntax that no longer should be applied is very intuitive.

**Comment by bitst0rm** [comment]
Thanks for your bug report @MatthiasPortzel 
The syntax part has been entirely removed.
You can now use "remember_session": true without encountering any issues with syntax packages.
Released version 1.1.2 as a hotfix to address this issue.
