### ISSUE TITLE
in sublime install package search 'Formatter' ,not show in search result list when sublime text version 4

### ISSUE THREAD

**Issue by awebc** [bitst0rm-pub/Formatter#46]
Formatter
by [bitst0rm-pub](https://packagecontrol.io/browse/authors/bitst0rm-pub) ST3
only ST3,NOT ST4,

**Comment by bitst0rm** [comment]
Hi @awebc 
Thank you for pointing out.
I am using the latest Sublime Text 4 (Build 4169) for development and could not reproduce this issue.
On https://packagecontrol.io if i type `formatter:4` i got the result as expected.
And the version `1.1.10` on this website is also matched the `tag` 1.1.10 on Github.
The label `ST3` indicates the minimum supported version, also min. Sublime Text 3,  include 4+
I recently checked it via Package Control > Install Package and could install it as usual:
<img width="1196" alt="screenshot" src="https://github.com/bitst0rm-pub/Formatter/assets/5733550/40419744-12b6-4c11-b949-360e1326879e">
