### ISSUE TITLE
Options greyed out - disabled

### ISSUE THREAD

**Issue by alemarengo** [bitst0rm-pub/Formatter#48]
Hi.
Is there a why I got greyed out options after fresh install?
Maybe a conflicting package?
Actually I have: Compare side-by-side; Highligh Duplicates; JsFormat.

**Comment by bitst0rm** [comment]
Hi @alemarengo 

I have recently released the new version 1.2.0 just before to know about your post here.
The new version should be on Package Control website within 1 hour, i guess.
It includes a new generic method to add plugins without coding and a fix that should address this issue.
Please update to this version to see if it is get fixed, Thanks.

The Changelog is here: https://github.com/bitst0rm-pub/Formatter/blob/master/messages/1.2.0.txt

Update: 1.2.0 already fixed this bug.
Please just feel free to re-open it.
