### ISSUE TITLE
Project local config

### ISSUE THREAD

**Issue by AnnanFay** [bitst0rm-pub/Formatter#50]
I'm trying to setup project config which works automatically for new systems / developers. Ideally I can say "Install the Formatter plugin and everything will work".

Is this possible? It was not clear to me from the help file, and my own experimentation, how to enable formatters outside of User's own personal settings.

What I've tried:

- Local `./Formatter.sublime-settings` - no effect
- Local `./ProjectName.sublime-project` - tried putting in `.settings.Formatter` and `.Formatter` - no effect
- Created empty `./.cfgignore` file - no effect

I guess when the help mentions "Per-project Config" it's about plugin config and not Formatter config?

**Comment by bitst0rm** [comment]
Closed as `.sublime-project` is supported in 1.4.0
