### ISSUE TITLE
Erlang formatter `efmt` doesn't work when used as a `rebar3` plugin

### ISSUE THREAD

**Issue by verbit** [bitst0rm-pub/Formatter#55]
When trying to format Erlang code, _Formatter_ correctly identifies `rebar3 efmt` as the available formatter, however, `rebar3 efmt` doesn't support reading from stdin as of now https://github.com/sile/efmt/issues/94.

Relevant logs:
```
▋[Formatter](formatter.py#L16): [DEBUG] Syntax: erlang | Scope: source.erlang meta.preprocessor.namespace.erlang punctuation.definition.keyword.erlang
▋[Formatter](formatter.py#L17): [DEBUG] UID: efmt (method: module) | Target: /path/to/mymod.erl
▋[Formatter](common.py#L350): [DEBUG] Global executable found: /usr/bin/rebar3
▋[Formatter](formatter_efmt.py#L39): [DEBUG] Command: ['/usr/bin/rebar3', 'efmt', '-']
▋[Formatter](common.py#L685): [STATUS] File not formatted due to an error (exitcode=1).
▋[Formatter](main.py#L612): [STATUS] ❌ Formatting failed. 😢💔
```

Shall this limitation be added to the docs or is there a way to work around that in _Formatter_?

**Comment by bitst0rm** [comment]
Hi @verbit 

Thank you for reporting this bug.
From the link provided, it appears that `rebar3` is **not** necessary for using `efmt`, so I will remove the `rebar3` detection part.

Without creating a patch or changing Formatter, this works for me:

```js
        "efmt": {
            "enable": true,
            "syntaxes": ["erlang"],
            "executable_path": ["/Users/admin/Downloads/efmt"]
            /* opinionated, no config */
        },
```
Alternatively, if `efmt` is in your `PATH`, this should work too:

```js
        "efmt": {
            "enable": true,
            "syntaxes": ["erlang"],
            "executable_path": ["efmt"]
            /* opinionated, no config */
        },
```

**Comment by verbit** [comment]
> I will remove the rebar3 detection

Thanks!

> it appears that rebar3 is not necessary for using efmt

Correct. Though, the tooling is greatly simplified when using the `rebar3` version (no need to manually download `efmt` and set up the paths). So I would definitely be happy if the `rebar3` detection would be re-enabled once the upstream issue is fixed. :slightly_smiling_face:

**Comment by bitst0rm** [comment]
> So I would definitely be happy if the `rebar3` detection would be re-enabled once the upstream issue is fixed. 🙂

Then we do not need to change anything. 🙂
I have reverted the patch with removing `rebar3`

If you want to use without rebar3, then you can adjust so:
- `"executable_path": ["/Users/admin/Downloads/efmt"]`
- `"executable_path": ["efmt"] `(on PATH, auto detection)

With rebar3 in the future:
- `"executable_path": ["/path/to/rebar3"]`
- `"executable_path": ["rebar3"] `(on PATH, auto detection)
- `"executable_path": null` (on PATH, auto detection)

**Comment by verbit** [comment]
Everything you say is correct, but my point is this: The next person trying to use the _Formatter_ with `rebar3 efmt` will be confused because it doesn't work, even though _Formatter_ is doing everything correctly.

So temporarily removing the `rebar3`-flavored `efmt` actually makes sense to me. Alternatively, the situation could be described in the docs (a la: `rebar3 efmt` doesn't work right now, so make sure to use plain `efmt`, as per your comment above).

**Comment by bitst0rm** [comment]
ahh, i see. I will add a note to the comment like this:

```js
        "efmt": {
            "executable_path": ["/path/to/bin/efmt (standalone bin)"]
            /* opinionated, no config. no rebar3 upstream support, use efmt standalone instead. requires efmt on PATH if omit interpreter_path */
        },
```
Additionally, I will temporarily remove the rebar3-`flavored` efmt since it appears that the developer is not planning to add support in the near future.
We can always add it back in the future if that changes.

Formatter will be rolled out as 1.14.15 today with these changes and improved console coloring syntaxes.

**Comment by bitst0rm** [comment]
I am closing this since version 1.14.15 has been rolled out.
Thanks for your feedback 👍
