### ISSUE TITLE
auto_format_config not defined

### ISSUE THREAD

**Issue by the-ge** [bitst0rm-pub/Formatter#57]
Hello,

I noticed "auto_format_config not defined" messages in the console. They stopped after changing
'_auto_format_config=auto_format_config_' argument to
'_auto_format_config=_**self.**_auto_format_config_'
in `core/common.py`:531 (in the `create_tmp_file()` method):
```Python
            uid, syntax = SyntaxHandler(view=self.view, uid=self.uid, region=self.region, auto_format_config=auto_format_config).get_assigned_syntax()
```
to
```Python
            uid, syntax = SyntaxHandler(view=self.view, uid=self.uid, region=self.region, auto_format_config=self.auto_format_config).get_assigned_syntax()
```
I know just enough Python to be dangerous, so I apologize if I'm missing something obvious :smile:

**Comment by bitst0rm** [comment]
Hi @the-ge 

Thank you for your bug report.
You are absolutely correct; it is indeed a bug due to the missing `self` value.
I have fixed it and released a new version.
So i am closing this right now.
