### ISSUE TITLE
Temporary file problem

### ISSUE THREAD

**Issue by husanjun** [bitst0rm-pub/Formatter#58]
Thank you for providing the plugin

At present, the temporary file path is in the project directory, which will flash quickly when used. 
Can you put the temporary file into the temporary file of the system

**Comment by bitst0rm** [comment]
Hi @husanjun 

Thank you for your bug report.
I have fixed it and will release a new version within a few hours today.

**Comment by bitst0rm** [comment]
@husanjun 
I have finished the latest work for the new version today. [CHANGELOG.md](https://github.com/bitst0rm-pub/Formatter/blob/master/CHANGELOG.md)
New version has been recently rolled out, Package Control will need a little time to see the update.

There are two new setting options `"close_console_on_success"` and  `"show_words_count": {"use_short_label": false}` you can you, if you already have had Formatter before.
