### ISSUE TITLE
Formatter affects other plugins

### ISSUE THREAD

**Issue by husanjun** [bitst0rm-pub/Formatter#63]
Hi, bitst0rm

After the Formatter is enabled, use the LSP-related plugin(such as lsp , lsp-pyright), and then go to definition, 
which seems to go where it was last time (close the definition page and try a few more times), 
but after the formatter is disabled, it works fine

**Comment by bitst0rm** [comment]
Hi @husanjun 

I think you are talking about this feature:
```
    // Remember and restore cursor position, selections and bookmarks
    // each time a file is closed and re-opened.
    // This is helpful to resume your work from where you left off.
    // It does not remember any sublime sessions as name might suggest.
    "remember_session": true,
```
you can of course disable it.

**Comment by husanjun** [comment]
> Hi @husanjun
> 
> I think you are talking about this feature:
> 
> ```
>     // Remember and restore cursor position, selections and bookmarks
>     // each time a file is closed and re-opened.
>     // This is helpful to resume your work from where you left off.
>     // It does not remember any sublime sessions as name might suggest.
>     "remember_session": true,
> ```
> 
> you can of course disable it.

I disabled it and it worked, Thanks
