### ISSUE TITLE
fail to use autopep8 to format python source code in some case

### ISSUE THREAD

**Issue by karma-sun** [bitst0rm-pub/Formatter#67]
fail to use autopep8 to format some python source code,for example code below:
a=r'(名称|片名)：'
but  use autopep8 in terminal to format it is no problem

**Comment by bitst0rm** [comment]
Hi @karma-sun 

Thank you for your bug report.
I was able to reproduce the issue and have reverted to the original code, which has been working reliably for years, to address it.
I will roll out the new version in the next few hours, along with other optimizations.
